- .gitignore
- pom.xml
- vaadin-services-demo/pom.xml
- vaadin-services-demo/src/main/java/com/vaadin/services/VaadinServiceDemoApplication.java
- vaadin-services-demo/src/test/java/com/vaadin/services/VaadinServiceDemoApplicationTests.java
- vaadin-services/pom.xml
- vaadin-services/src/main/java/com/vaadin/services/DummyClass.java
- vaadin-services/src/test/java/com/vaadin/services/DummyClassTest.java
Connect to #26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-services/29)
> Init maven modules

- vaadin-services-demo/src/main/java/com/vaadin/services/VaadinServicesDemoApplication.java
- vaadin-services-demo/src/test/java/com/vaadin/services/VaadinServicesDemoApplicationTests.java
- vaadin-services/pom.xml
- vaadin-services/src/main/java/com/vaadin/services/DummyClass.java
- vaadin-services/src/test/java/com/vaadin/services/DummyClassTest.java
This PR fixes some issues showing up after the sonarqube validation setup. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-services/32)
> Fix sonarqube issues

- README.md
- pom.xml
- vaadin-connect-demo/pom.xml
- vaadin-connect-demo/src/main/java/com/vaadin/connect/VaadinConnectDemoApplication.java
- vaadin-connect-demo/src/test/java/com/vaadin/connect/VaadinConnectDemoApplicationTests.java
- vaadin-connect/pom.xml
- vaadin-connect/src/main/java/com/vaadin/connect/DummyClass.java
- vaadin-connect/src/test/java/com/vaadin/connect/DummyClassTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/36)
> Rename the project from vaadin-services to vaadin-connect

- pom.xml
- vaadin-connect-demo/pom.xml
- vaadin-connect/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/38)
> Adjust project dependencies

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
Fixes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/45)
> feat(frontend): Add accessToken support to ConnectClient

- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoRestService.java
- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinOAuthConfiguration.java
- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectOauthTokenIT.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/EnableVaadinConnectOAuthServer.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfiguration.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurer.java
- vaadin-connect/src/test/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurerTest.java
Fixes #46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/50)
> Adding a new annotation for simplifying oauth configuration

- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectOauthTokenIT.java
- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectProperties.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfiguration.java
Fixes #16
The expiration and signature validations have been done by default in Spring.
This PR only adds the validation for required claims and some IT tests with modified tokens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/52)
> Validate access token backend

- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectProperties.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfiguration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/56)
> Use a generated secret random-key when none is provided

- vaadin-connect/src/main/java/com/vaadin/connect/generator/DefaultClientJsGenerator.java
- vaadin-connect/src/main/java/com/vaadin/connect/generator/Generator.java
- vaadin-connect/src/main/resources/com/vaadin/connect/generator/connect-client.default.js.template
- vaadin-connect/src/test/java/com/vaadin/connect/generator/DefaultClientJsGeneratorTest.java
- vaadin-connect/src/test/java/com/vaadin/connect/generator/GeneratorTest.java
- vaadin-connect/src/test/resources/com/vaadin/connect/generator/application.properties.for.testing
- vaadin-connect/src/test/resources/com/vaadin/connect/generator/expected-connect-client-custom.js
- vaadin-connect/src/test/resources/com/vaadin/connect/generator/expected-connect-client-default.js
Fixes #24 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/54)
> Generate connect-client-default.js

- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java
- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectControllerIT.java
- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/EnableVaadinConnectOAuthServer.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthAclChecker.java
- vaadin-connect/src/test/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurerTest.java
- vaadin-connect/src/test/java/com/vaadin/connect/oauth/VaadinConnectOauthAclCheckerTest.java
Fixes #13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/53)
> Adding role-based ACL to vaadin-service methods

- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectOauthTokenIT.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurer.java
- vaadin-connect/src/test/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurerTest.java
Fixes #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/65)
> Fix refresh_token authentication

- frontend/connect/.eslintrc.json
- frontend/connect/package.json
- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- frontend/connect/test/utils.js
- vaadin-connect-demo/frontend/index.js
- yarn.lock
Connected to #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/72)
> Implement `credentials` callback

- doc/javascript-generator.asciidoc
Connect to #20 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/75)
> Add documentation for js generator

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectJsGenerator.java
- vaadin-connect-maven-plugin/src/main/resources/com/vaadin/connect/plugin/generator/ESModuleApiTemplate.mustache
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-first-class-multiple-tags.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-no-jsdoc.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-partly-jsdoc.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-second-class-multiple-tags.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/no-jsdoc-operation.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/parameters-and-return-jsdoc.json
Connect to #20 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/83)
> Only show JsDoc when there is JsDoc

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectJsGenerator.java
- vaadin-connect-maven-plugin/src/main/resources/com/vaadin/connect/plugin/generator/ESModuleApiTemplate.mustache
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-multiple-lines-description.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/multiplelines-description.json
This helps the generated template in https://github.com/vaadin/base-starter-connect/pull/12 looks better
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/86)
> Add multiple lines helper for template

- frontend/connect/.eslintrc.json
- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- frontend/connect/test/utils.js
- vaadin-connect-demo/frontend/index.js
Fixes #12
Fixes #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/87)
> implement refreshToken and stayLoggedIn

- vaadin-connect-demo/scripts/start/backend.js
Similar PR will be done in base-starter-connect after the review is passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/91)
> Fix backend initial startup

- doc/vaadin-connect-maven-plugin.asciidoc
- vaadin-connect-demo/.eslintrc.json
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.js
Closes #74
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/88)
> Add direct Vaadin Connect client usage example

- frontend/connect/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/93)
> Add README in connect package

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/90)
> remove public accessToken. Fix corrupted token

- frontend/connect/intern.json
- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/intern.json
Fixes #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/92)
> feat(demo) add SauceLabs tests environments

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
Fixes #78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/105)
> Expose access token data in the client

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
Fixes #100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/110)
> feat(frontend): Add a call option to omit authorization requirement

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/GeneratorTestClass.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
Fix #104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/109)
> Fix bug full qualified name type in generator

- pom.xml
- vaadin-connect-demo/pom.xml
- vaadin-connect-maven-plugin/pom.xml
- vaadin-connect/pom.xml
TODO comment ticket: https://github.com/vaadin/vaadin-connect/issues/112
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/111)
> Check jacoco coverage in each module separately

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/123)
> feat(generator): sort OpenApi paths alphabetically

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/GeneratorTestClass.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
Closes #126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/127)
> fix(generator): consider nested classes when generating

- vaadin-connect-maven-plugin/src/main/resources/com/vaadin/connect/plugin/generator/ESModuleApiTemplate.mustache
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-default-class-no-tag.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-first-class-multiple-tags.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-multiple-lines-description.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-no-jsdoc.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-partly-jsdoc.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-second-class-multiple-tags.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/parameters-and-return-jsdoc.json
Fixes #101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/122)
> feat(generator): skip credentials if service is anonymous

- vaadin-connect-demo/.eslintrc.json
- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/frontend/.eslintrc.json
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.js
Fixes #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/121)
> feat(demo): add check anonymous access button and integration test

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/GeneratorTestClass.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorAnonymousAllowedTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
Closes #119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/129)
> feat(generator): Do not generate @DenyAll marked methods

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.js
Close #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/130)
> feat(frontend) add login api for ConnectClient

- frontend/connect/package.json
- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- frontend/connect/test/utils.js
Fixes #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/139)
> feat(auth) add logout method to js API

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- yarn.lock
Fixes #132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/148)
> feat(login) re-use login promise in parallel calls

- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
Closes #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/155)
> feat(backend): Make json mapper qualifier public

- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
- vaadin-connect/src/test/java/com/vaadin/connect/VaadinConnectControllerTest.java
Closes #149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/156)
> feat(backend): Add logging to Vaadin Connect controller

- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/frontend/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/161)
> test(demo): Remove logout todos

- doc/default-client.asciidoc
- doc/javascript-generator.asciidoc
- vaadin-connect-demo/frontend/index.js
- vaadin-connect-maven-plugin/src/main/resources/com/vaadin/connect/plugin/generator/ESModuleApiTemplate.mustache
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorAnonymousAllowedTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-default-class-no-tag.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-first-class-multiple-tags.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-multiple-lines-description.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-no-jsdoc.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-partly-jsdoc.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-second-class-multiple-tags.js
Fixes #114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/160)
> feat(ide) move class methods to module level, remove wrap class

- pom.xml
- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
- vaadin-connect/src/test/java/com/vaadin/connect/VaadinConnectControllerTest.java
- vaadin-connect/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Closes #112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/164)
> test(controller): Add controller tests

- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.js
- vaadin-connect-demo/intern.json
Fixes #159
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/165)
> fix(demo): improve e2e tests reliablility

- doc/type-conversion.asciidoc
- rewrite the intro paragraphs to type conversion doc
- emphasize UTF-16 encoding in string / char conversion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/182)
> update the docs intro and describe UTF-16 string conversion

- doc/type-conversion.asciidoc
* add documentation for Java to JS types
* reorder primitive types
* use simple present tense
* add common Noncompliant values
Fix #115 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/183)
>  doc(typeconversion): add documentation for Java to JS types

- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/package.json
- vaadin-connect-demo/pom.xml
- vaadin-connect-demo/webpack.config.js
- yarn.lock
Fixes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/186)
> feat(prod) Run IT against client bundle. Add bundle to deployable .jar

- frontend/connect/package.json
- frontend/connect/test/connect-client.spec.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/199)
> chore(test) remove workaround for abort in fetch-mock

- doc/type-conversion.asciidoc
- vaadin-connect-maven-plugin/pom.xml
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/OpenApiParserTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/collectionservice/CollectionTestService.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-collection-service.json
Fix #113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/197)
> refactor(generator): use ResolvedType to create Schema

- vaadin-connect-demo/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/201)
> chore(IT): Use yarn instead of npm

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectClientGenerator.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/esmodule-generator-OneServiceOneMethod.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/esmodule-generator-TwoServicesThreeMethods.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-FooBarService.js
Fix #137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/203)
> fix(generator): clean generated folder before generating new files

- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
- vaadin-connect/src/test/java/com/vaadin/connect/VaadinConnectControllerTest.java
- vaadin-connect/src/test/java/com/vaadin/connect/testservice/BridgeMethodTestService.java
Fix #162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/207)
> fix(controller): use correct method descriptor for overridden methods

- doc/vaadin-connect-maven-plugin.asciidoc
- vaadin-connect-demo/scripts/start/backend.js
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/EsModuleGeneratorMojo.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/OpenApiSpecGeneratorMojo.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/VaadinClientGeneratorMojo.java
Fix #219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/222)
> fix(generator): tie the generations to compile phase

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/VaadinClientGeneratorMojo.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectClientGenerator.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectJsGenerator.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/VaadinConnectClientGeneratorTest.java
Fix #221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/223)
> fix(generator): clean stale generated files instead of whole folder

- vaadin-frontend-server/src/main/java/com/vaadin/frontend/server/VaadinFrontendInterceptor.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/225)
> fix(frontend) return false in preHandle on not-found

- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/234)
> chore(tests) remove debug logs in generator tests

- vaadin-connect-demo/e2e/.eslintrc.json
- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/intern.json
- vaadin-connect-demo/package.json
Fixes #227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/233)
> fix(tests): use pollUntil instead of fixed timeouts in tests

- vaadin-connect-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/236)
> chore(demo): change path of webpack output in pom

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectJsGenerator.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorTestClass.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
Fix #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/239)
> fix(generator): preserve parameter's javadoc of bean types

- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-frontend-server/src/main/java/com/vaadin/frontend/server/EnableVaadinFrontendServer.java
- vaadin-frontend-server/src/main/java/com/vaadin/frontend/server/VaadinFrontendInterceptor.java
- vaadin-frontend-server/src/main/java/com/vaadin/frontend/server/VaadinFrontendRouteMatcher.java
- vaadin-frontend-server/src/test/java/com/vaadin/frontend/server/VaadinFrontendServerTest.java
Fixes #178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/240)
> feat(frontendserver) make vaadin-frontend-server configurable

- vaadin-connect-demo/pom.xml
Otherwise each time app is traspiled java server is restarted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/246)
> fix(devmode) remove webpack output folder from spring-boot config

- doc/README.asciidoc
Include the 'Getting Started' page into the Table of Contents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/248)
> add a link to 'Getting Started' into doc/README

- pom.xml
- vaadin-connect-demo/pom.xml
A follow-up for https://github.com/vaadin/base-starter-connect/pull/52 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/260)
> chore(build): Adjust repositories

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectJsGenerator.java
- vaadin-connect-maven-plugin/src/main/resources/com/vaadin/connect/plugin/generator/ESModuleApiTemplate.mustache
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-GeneratorTestClass.js
Closes #70
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/249)
> feat(generator): add user defined types information to the js generated

- vaadin-connect-demo/package.json
- vaadin-connect-demo/scripts/start/backend.js
Changes already applied to starter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/264)
> chore(test): do not run api-browser in test

- pom.xml
- vaadin-frontend-server/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/268)
> chore(frontend): enable coverage in frontend-server module

- doc/security.asciidoc
- doc/vaadin-connect-maven-plugin.asciidoc
- vaadin-connect-demo/pom.xml
- vaadin-connect-demo/src/main/resources/application.properties
- vaadin-connect-maven-plugin/pom.xml
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/TokenSigningKeyGeneratorMojo.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/VaadinConnectMojoBase.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiSpecGenerator.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/TokenSigningKeyGenerator.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectClientGenerator.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/TestUtils.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/ESModuleGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/OpenApiSpecGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/TokenSigningKeyGeneratorTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/VaadinConnectClientGeneratorTest.java
Fix #238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/266)
> feat(generator): generate a random token-signing-key if necessary

- pom.xml
- vaadin-connect-demo/pom.xml
Follow up https://github.com/vaadin/base-starter-connect/pull/61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/271)
> chore(build): use latest maven central url

- doc/how-to-add-api-endpoint.asciidoc
- doc/vaadin-connect-exceptions.asciidoc
Closes #252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/270)
> Add API endpoint docs

- doc/README.asciidoc
- doc/getting-started.asciidoc
- doc/how-to-add-api-endpoint.asciidoc
- doc/how-to-add-login-form.asciidoc
Fix #254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/273)
> doc(howto): add login-form howto

- vaadin-connect-demo/e2e/demo.spec.js
- vaadin-connect-demo/intern.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/275)
> fix(e2e): avoid false positive result when using pollUntil

- vaadin-connect-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/280)
> fix(eclipse): add generate-token-signing-key to m2eclipse metadata

- doc/README.asciidoc
- doc/how-to-setup-authentication-backend.asciidoc
- doc/how-to-use-an-api-endpoint.asciidoc
- doc/security.asciidoc
Fix #261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/278)
> doc(authentication): add doc for setting up authentication in backend

- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- vaadin-connect-demo/src/main/resources/application.properties
- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectControllerIT.java
- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectOauthTokenIT.java
- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectProperties.java
- vaadin-connect/src/main/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurer.java
- vaadin-connect/src/test/java/com/vaadin/connect/oauth/VaadinConnectOAuthConfigurerTest.java
Fixes #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/279)
> feat(oauth): remove client-secret requirement in oauth requests

- vaadin-connect-demo/pom.xml
- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectControllerIT.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/GeneratorUtils.java
- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
Closes #220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/285)
> fix(connect): accept empty content type headers

- README.asciidoc
- doc/frontend-server.asciidoc
- doc/how-to-add-login-form.asciidoc
- doc/how-to-setup-authentication-backend.asciidoc
- doc/how-to-use-an-api-endpoint.asciidoc
- doc/security.asciidoc
- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinOAuthConfiguration.java
- vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectOauthTokenIT.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/TestUtils.java
- vaadin-frontend-server/src/test/java/com/vaadin/frontend/server/VaadinFrontendServerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/288)
> style: fix typos

- vaadin-connect-demo/src/main/resources/application.properties
- vaadin-connect-maven-plugin/pom.xml
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/OpenApiParserTest.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/denyall/DenyAllClass.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-denyall-service.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/286)
> fix(generator): Fix wrong DenyAll annotation usage

- vaadin-connect-demo/intern.json
- vaadin-connect-demo/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/290)
> fix(e2e): disable Safari 12 for now, fix IE 11 startup

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/esmodule-generator-OneServiceOneMethod.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/esmodule-generator-TwoServicesThreeMethods.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-collection-service.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-denyall-service.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/expected-openapi.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/parameters-and-return-jsdoc.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/reserved-words.json
Fixes #274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/292)
> fix(openapi): describe authorization as OAuth2 with password

- doc/README.asciidoc
- doc/how-to-add-api-endpoint.asciidoc
- doc/how-to-build-for-production.asciidoc
Fixes #257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/289)
> doc(howto): add build for production howto

- doc/README.asciidoc
- doc/getting-started.asciidoc
- doc/how-to-add-api-endpoint.asciidoc
- doc/how-to-add-login-form.asciidoc
- doc/how-to-browse-api.asciidoc
- doc/how-to-build-for-production.asciidoc
- doc/how-to-secure-api-endpoint.asciidoc
- doc/how-to-setup-authentication-backend.asciidoc
- doc/how-to-use-an-api-endpoint.asciidoc
Fixes #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/293)
> docs: add how-to-browse-api.asciidoc

- doc/README.asciidoc
- doc/how-to-add-api-endpoint.asciidoc
- doc/how-to-add-login-form.asciidoc
- doc/how-to-browse-api.asciidoc
- doc/how-to-build-for-production.asciidoc
- doc/how-to-create-spa.asciidoc
- doc/how-to-secure-api-endpoint.asciidoc
- doc/how-to-setup-authentication-backend.asciidoc
- doc/how-to-use-an-api-endpoint.asciidoc
Fix #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/294)
> doc(howto): add how-to for SPA

- doc/README.asciidoc
- doc/client-middleware.asciidoc
- frontend/connect/src/connect-client.js
- frontend/connect/test/connect-client.spec.js
- frontend/connect/test/utils.js
- vaadin-connect-demo/package.json
Fixes #202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/299)
> feat(client): add support for custom middlewares

- vaadin-connect-demo/frontend/polyfills.js
- vaadin-connect-demo/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/300)
> fix(demo): use full fetch polyfill

- README.asciidoc
to address the DX feedback
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/303)
> do not claim Vaadin Connect includes a REST server

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectJsGenerator.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/json/JsonTestService.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.js
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-openapi-custom-application-properties.json
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-openapi.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/304)
> fix(generator): enable generating request user types

- frontend/connect/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/310)
> Require non-broken version of stats

- frontend/connect/scripts/version.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/311)
> fix(client): stage connect-meta.ts change in version commit

- frontend/connect/src/connect-client.ts
- frontend/connect/src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/314)
> fix(client): export TypeScript interfaces from package

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-default-class-no-tag.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-first-class-multiple-tags.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-multiple-lines-description.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-second-class-multiple-tags.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/collectionservice/expected-CollectionService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.ts
- yarn.lock
Fixes #312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/320)
>  fix(generator): generate correct array type

- vaadin-connect-demo/e2e/demo.spec.ts
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/323)
> fix(demo): IE 11 errors for Number.parseInt and other warnings

- doc/type-conversion.asciidoc
- vaadin-connect-demo/e2e/demo.spec.ts
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.ts
- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/inheritedmodel/expected-model-com.vaadin.connect.plugin.generator.services.inheritedmodel.InheritedModelService.ChildModel.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/inheritedmodel/expected-model-io.swagger.v3.oas.models.ExternalDocumentation.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/inheritedmodel/expected-model-io.swagger.v3.oas.models.media.Discriminator.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/inheritedmodel/expected-model-io.swagger.v3.oas.models.media.Schema.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/inheritedmodel/expected-model-io.swagger.v3.oas.models.media.XML.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-model-com.vaadin.connect.plugin.generator.services.json.JsonTestService.User.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/model/expected-ModelService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/sameclassname/expected-SameClassNameService.ts
Fixes #341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/348)
>  fix(plugin): generate map type as object

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
- vaadin-connect-maven-plugin/src/main/resources/com/vaadin/connect/plugin/generator/TypeScriptApiTemplate.mustache
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/model/ComplexReturnTypeService.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/model/ComplexTypeParamsService.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/model/expected-ComplexReturnTypeService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/model/expected-ComplexTypeParamsService.ts
Fixes #338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/352)
>  fix(plugin): generate imports for complex type parameters

- doc/type-conversion.asciidoc
- vaadin-connect-demo/e2e/demo.spec.ts
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.ts
- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiObjectGenerator.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/datetime/DateTimeService.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/datetime/DateTimeServiceTest.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/datetime/expected-DateTimeService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-model-com.vaadin.connect.plugin.generator.services.json.JsonTestService.Status.ts
Fixes #337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/355)
>  fix(plugin): generate date and datetime type as string

- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
- vaadin-connect/src/main/java/com/vaadin/connect/exception/VaadinConnectValidationException.java
- vaadin-connect/src/test/java/com/vaadin/connect/VaadinConnectControllerTest.java
- vaadin-connect/src/test/java/com/vaadin/connect/exception/VaadinConnectValidationExceptionTest.java
Fixes #193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/359)
>  feat(validation): throw validation error when deserialization fails

- frontend/connect-scripts/src/commands/start/backend.ts
Closes https://github.com/vaadin/base-starter-connect/issues/81
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/360)
> fix(scripts): Adjust the backend failure console output

- frontend/connect/src/connect-client.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/361)
> docs(connect): Add missing tsdocs

- vaadin-connect-demo/e2e/demo.spec.ts
- vaadin-connect-demo/e2e/tslint.json
- vaadin-connect-demo/frontend/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/365)
> fix(e2e): typing hangs on Android in SauceLabs

- tsconfig.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/364)
> chore: enable dynamic imports in TypeScript code

- vaadin-connect-demo/webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/367)
> fix(e2e): restore WC polyfills in demo frontend, needed in IE11

- vaadin-connect-demo/e2e/demo.spec.ts
- vaadin-connect-demo/frontend/index.html
- vaadin-connect-demo/frontend/index.ts
- vaadin-connect-demo/package.json
- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java
- vaadin-connect/pom.xml
- vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java
- vaadin-connect/src/test/java/com/vaadin/connect/VaadinConnectControllerTest.java
Closes #215
Closes #217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/366)
> feat(validation): Validate incoming service requests

- doc/typescript-generator.asciidoc
- vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiObjectGenerator.java
- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
Fixes #342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/378)
>  fix(plugin): fetch valid fields from only class declaration

- frontend/connect/src/connect-client.ts
- frontend/connect/test/connect-client.spec.js
- vaadin-connect-demo/package.json
Closes #308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/374)
> feat(connect): Add new login api method that does not ask for credentials

- vaadin-connect-demo/frontend/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/382)
> test(demo): remove valueAsNumber since it always 0 in IE11

- frontend/connect/src/connect-client.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/384)
> Keep original validation error message in the error object

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
- vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/notnull/NotNullService.java
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/notnull/expected-NotNullService.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/notnull/expected-model-com.vaadin.connect.plugin.generator.services.notnull.NotNullService.ParameterType.ts
- vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/notnull/expected-model-com.vaadin.connect.plugin.generator.services.notnull.NotNullService.ReturnType.ts
Fixes #386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/387)
> fix(plugin): get nested type from nullable wrapper even if not null

- frontend/connect-scripts/src/lib/ensureExecutable.ts
- frontend/connect-scripts/src/lib/spawn/maven.ts
Fixes #379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/383)
> fix(scripts): make mvnw executable before running it

- doc/README.asciidoc
- doc/service-methods-validation.asciidoc
Closes #282 
Closes #281 
I decided to unite both tickets in the same PR since there's not much to document on the topic hence no need to split it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/385)
> docs(validation): Add a documentation on Vaadin Connect validation functionality

- frontend/connect-scripts/src/lib/spawn.ts
- frontend/connect-scripts/src/lib/spawn/intern.ts
- frontend/connect-scripts/src/lib/spawn/webpack.ts
Fixes #389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/390)
> fix(scripts): fix running on windows

- vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
Fixes #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/393)
> fix(generator): generate correct import paths on Windows

- doc/getting-started.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/400)
> docs(connect): fix TS errors in the Getting Started snippets

- doc/frontend-server.asciidoc
- pom.xml
- vaadin-connect-demo/pom.xml
Related to vaadin/platform#766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/423)
> Use https for Maven repositories

- README.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/429)
> Update README so project can be archived
