vaadin/vaadin-connect

pom.xml, vaadin-connect-demo/src/test/java/com/vaadin/connect/demo/VaadinConnectControllerIT.java, vaadin-connect/pom.xml, vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java, vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectControllerConfiguration.java, vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectProperties.java
Closes #23 
Also hide all Vaadin Connect services behind `/connect` base url to avoid conflicts with other controllers, such as `oauth`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/42)
=> Allow to customize Vaadin Connect base url

vaadin-connect/src/main/java/com/vaadin/connect/generator/OpenApiJavaParserImpl.java, vaadin-connect/src/main/java/com/vaadin/connect/generator/VaadinConnectJsGenerator.java, vaadin-connect/src/main/resources/com/vaadin/connect/generator/ESModuleApiTemplate.mustache, vaadin-connect/src/test/resources/com/vaadin/connect/generator/expected-openapi-custom-application-properties.json, vaadin-connect/src/test/resources/com/vaadin/connect/generator/expected-openapi.json, vaadin-connect/src/test/resources/com/vaadin/connect/generator/get-operation-openapi.json, vaadin-connect/src/test/resources/com/vaadin/connect/generator/multiple-tags-operation.json, vaadin-connect/src/test/resources/com/vaadin/connect/generator/no-tag-operation.json, vaadin-connect/src/test/resources/com/vaadin/connect/generator/wrong-input-path-openapi.json
Instead of using `x-vaadin-services` extension for storing javadoc of service classes, we can use [TagObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#tagObject) to describe the tags which has been declared in each operation.
Connect to #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/73)
=> Use tags description

vaadin-connect-demo/pom.xml
Avoid failing when `mvn clean` is called before `mvn install`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/89)
=> Add a snapshot plugin repo

vaadin-connect-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
It prevents eclipse marking the project with `Plugin execution not covered by lifecycle configuration` errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/108)
=> m2eclipse integration

doc/vaadin-connect-maven-plugin.asciidoc
Closes #19
Closes #21 
The example is added in https://github.com/vaadin/base-starter-connect/pull/25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/117)
=> Add automatic resources generation example to the documentation

vaadin-connect-maven-plugin/pom.xml
swagger-codegen plugin's dependency brings in the logback logger
implementation and slf4j-simple implementation gets ignored
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/128)
=> chore(generator): Remove unused logging dependency

vaadin-connect-maven-plugin/pom.xml
This fixes the `java.lang.NoClassDefFoundError: javax/annotation/security/PermitAll` error that occurs when trying to use the plugin with maven 3.5.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/131)
=> chore(plugin): include javax.annotation-api into the plugin .jar

frontend/connect/src/connect-client.js, frontend/connect/test/connect-client.spec.js
Fix #102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/133)
=> fix(frontend): use credentials after receiving invalid_token response

vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java, vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/account/BeanWithTypeFromDependencies.java, vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/OpenApiSpecGeneratorMojo.java, vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiParser.java, vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiSpecGenerator.java, vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/collectionservice/CollectionTestService.java
Fix #209 
Fix #208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/211)
=> fix(generator): use project class path for type resolving in OpenAPI generator

doc/README.asciidoc, doc/security.asciidoc, doc/vaadin-connect-maven-plugin.asciidoc
Since the docs are not deployed anywhere yet, let's optimize them for GitHub:
- add a `README` file (not e.g. `Overivew`) because GitHub renders it automatically under the directory contents listing
- collect links to all existing documentation pages in one place so that there is a single link to all Vaadin Connect docs (and it can be shared with someone who is interested to try it out)
- include a link to the starter project into the same README file
This is a prerequisite for starting DX tests, because any tester would need a single entry point into the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/224)
=> doc(general): add a README file with a table of contents

vaadin-connect-demo/e2e/demo.spec.js, vaadin-connect-demo/static/README.txt
Fix #180 
- `a <a href="users"> link works correctly in both cases` => this has been skipped since it depends on #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/237)
=> test(e2e): add tests for loading static resources

doc/getting-started.asciidoc
- remove mentions of SPA
Vaadin Connect supports SPAs but does not require that the frontend is necessarily an SPA.
- remove a hard dependency on Spring
Spring is an implementation detail. Vaadin Connect should not use anything Spring-dependent in the public APIs, nor explicitly mention it in the documentation. It's OK to tell that the current version of Connect is implemented using Spring, but that should be kept as an implementation detail that could possibly change (without changing what Connect is).
- add a code snippet to show on the first screen
A picture tells a thousand words, and a code snippet is like a picture.
In my mind it is important to show a code snippet on the first screen of the 'What is Vaadin Connect' section.
- update the 'Why use Vaadin Connect' section
- 'Java …
=> review comments and suggestions

doc/README.asciidoc
add a missing `>` to fix the `Vaadin Connect Exceptions` link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/247)
=> fix a typo in doc/README

frontend/connect/src/connect-client.js
This fixes the error reported by running the [`jsdoc`](http://usejsdoc.org/) JSDoc comments processing tool on the project sources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/283)
=> fix a typo in the JSDoc format

vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-default-class-no-tag.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-first-class-multiple-tags.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-multiple-lines-description.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-second-class-multiple-tags.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/collectionservice/expected-CollectionService.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.ts
`array` is not a valid type in TS. At the very least, it should be either `Array<any>` or `any[]`, and preferably, it should also include the type information of the array items (e.g. `Array<number>` or `number[]`).
This is a partial fix for #312. It only fixes the generated type of method parameters (generate `any[]` instead of `array`). The type of the return values is still generated wrongly.
Related to #312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/313)
=> partial fix(generator): use correct TS array type for method parameters

README.asciidoc, doc/client-middleware.asciidoc, doc/default-client.asciidoc, doc/getting-started.asciidoc, doc/how-to-add-login-form.asciidoc, doc/how-to-create-spa.asciidoc, doc/how-to-use-an-api-endpoint.asciidoc, doc/security.asciidoc, doc/typescript-generator.asciidoc, frontend/connect/src/index.ts, vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/VaadinConnectMojoBase.java, vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-FooBarService.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-default-class-no-tag.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-first-class-multiple-tags.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-multiple-lines-description.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-no-tsdoc.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-partly-tsdoc.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/openapi/expected-second-class-multiple-tags.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/collectionservice/expected-CollectionService.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/denyall/expected-DenyAllService.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-GeneratorAnonymousAllowedTestClass.ts, vaadin-connect-maven-plugin/src/test/resources/com/vaadin/connect/plugin/generator/services/json/expected-JsonTestService.ts
It turns out, using explicit "*.ts" ending in imports errors in the compiler with: `error TS2691: An import path cannot end with a '.ts' extension. Consider importing './x' instead.`.
In curtain cases (only tsc, no webpack) we could use ".js" imports instead, but then Webpack is unhappy, because it cannot resolve a missing .js file import.
Dropping .ts extensions in all the imports seems to be the most consistent way, both Webpack and tsc support that.
Depends on #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/315)
=> fix: drop .ts extensions in the imports

vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoApplication.java, vaadin-connect-demo/src/main/java/com/vaadin/connect/demo/DemoVaadinService.java, vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/OpenApiObjectGenerator.java, vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/AbstractServiceGenerationTest.java, vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/denyall/DenyAllService.java, vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/json/JsonTestService.java, vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectController.java, vaadin-connect/src/main/java/com/vaadin/connect/VaadinConnectControllerConfiguration.java, vaadin-connect/src/main/java/com/vaadin/connect/auth/AnonymousAllowed.java, vaadin-connect/src/main/java/com/vaadin/connect/auth/VaadinConnectAccessChecker.java, vaadin-connect/src/main/java/com/vaadin/connect/auth/server/EnableVaadinConnectOAuthServer.java, vaadin-connect/src/main/java/com/vaadin/connect/auth/server/VaadinConnectOAuthConfiguration.java, vaadin-connect/src/main/java/com/vaadin/connect/auth/server/VaadinConnectOAuthConfigurer.java, vaadin-connect/src/test/java/com/vaadin/connect/VaadinConnectControllerTest.java, vaadin-connect/src/test/java/com/vaadin/connect/auth/VaadinConnectAccessCheckerTest.java, vaadin-connect/src/test/java/com/vaadin/connect/auth/server/VaadinConnectOAuthConfigurerTest.java, vaadin-connect/src/test/java/com/vaadin/connect/typeconversion/BaseTypeConversionIT.java
It should be possible to create an app with Vaadin Connect, that does not use the built-in OAuth server. The most trivial example of such an app would be one where anonymous access is allowed to all `@VaadinService`s.
The fix moves the access checker class closer to the core Vaadin Connect module, separating it from the OAuth server implementation class. The `@AnonymousAllowed` and `VaadinConnectAccessChecker` are in a different package from thedefault OAuth server because they can be used separately from it.
Fixes #242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/319)
=> make the built-in auth server optional

doc/getting-started.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/331)
=> docs: fix a typo in the path to `openapi.json` in 'Getting Started'

doc/type-conversion.asciidoc
This PR updated information for:
- Primitive types
- String
- Array + collection
- Map (need to verify after implementation is done in #341 )
- Date (need to verify after implementation is done in #337 )
Enum has not generated properly (see #350) so it's better to fix doc in that issue as well.
Fixes #309  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/346)
=> doc(typeconversion): update documentation for primitives, array, map

vaadin-connect-demo/e2e/demo.spec.ts, vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/model/ModelService.java, vaadin-connect-maven-plugin/src/test/java/com/vaadin/connect/plugin/generator/services/model/ShouldNotBeGenerated.java
Fixes #339.
Apparently, this PR doesn't fix the issue since it is not reproducible in the current state of the plugin (possibly fixed in #317). But I added a field into a test to make sure it won't happen again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/357)
=> test(plugin): verify that fields in services are not generated

frontend/connect-scripts/src/commands/start.ts
Closes https://github.com/vaadin/base-starter-connect/issues/80
For some strange reason, file watcher fails to be stopped when the situation as the one described in a ticket happens.
I've investigated and it seems that the logic is correct — we store the correct pid for the watcher and use it to kill the process, the process kill happens without any error but does not actually kill the watcher process.
The order of the processes did not matter also — as long as there's an error happening, the watcher is not stopped even though the `kill(watcherProcess.pid);` code is executed.
When there's no error, the watcher seems to be stopped correctly.
Considering all this, I've moved the watcher start to the very end, after all port-dependent processes are launched — this allows us not to start the …
=> fix(scripts): Run watcher as the last one

frontend/connect/src/connect-client.ts
Update the TS type definition for the credentials callback so that `undefined` is an allowed return value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/368)
=> fix(client): allow falsy return from credentials callback

vaadin-connect-maven-plugin/src/main/java/com/vaadin/connect/plugin/generator/VaadinConnectTsGenerator.java
Amends the partial fix done in https://github.com/vaadin/vaadin-connect/pull/393
Fixes #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/395)
=> fix(generator): generate correct import paths on Windows / part 2

frontend/connect-scripts/src/lib/spawn.ts, frontend/connect/test/connect-client.spec.js, vaadin-connect-demo/intern.json, yarn.lock
fix the security issues reported by `dependabot`
Affected packages:
- handlebars
- js-yaml
- fstream
- axios
Closes #410, #411, #412, #407, #408 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/413)
=> chore: upgrade npm dependencies

frontend/connect/package.json, yarn.lock
Fixes the eslint-utils security vulnerability https://github.com/mysticatea/eslint-utils/security/advisories/GHSA-3gx7-xhv7-5mx3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-connect/424)
=> chore: update npm dependencies
